export const data: Employee[] = [
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
  {
    name: "Xbox Elite Wireless Controller Series 2 – Black",
    category: "Games",
    stock: 12,
    price: 113,
    photo: "https://m.media-amazon.com/images/I/71vNw0EbrTL._SL1500_.jpg",
  },
  {
    name: "Nintendo Switch – OLED Model w/ Neon Red & Neon Blue Joy-Con",
    category: "Console",
    stock: 5,
    price: 78,
    photo: "https://m.media-amazon.com/images/I/51l2sun2aOL._SL1008_.jpg",
  },
  {
    name: "Star Wars Jedi: Survivor - PlayStation 5",
    category: "PS4",
    stock: 2,
    price: 49,
    photo: "https://m.media-amazon.com/images/I/61OlrxlXo0L.jpg",
  },
];
